kind: pipeline
type: docker
name: docs

steps:
  - name: build
    image: elixir:latest
    environment:
      MIX_ENV: dev
    commands:
      - mix local.hex --force
      - mix local.rebar --force
      - mix deps.get --only dev
      - mix deps.compile
      - mix docs
      - ln -s ../docs_config.js doc/docs_config.js

  - name: publish
    image: drillster/drone-rsync
    settings:
      hosts: [ soft.vub.ac.be ]
      user:
        from_secret: publish_ssh_user
      key:
        from_secret: publish_ssh_key
      source: doc/
      target: ~/public_html/skitter/docs/${DRONE_TAG:-latest}
      recursive: true
      delete: true
    when:
      ref:
        - refs/heads/develop
        - refs/tags/*
---

kind: pipeline
type: docker
name: notify-failure

clone:
  disable: true

steps:
- name: mail
  image: drillster/drone-email
  settings:
    host:
      from_secret: mail_host
    from:
      from_secret: mail_from
    username:
      from_secret: mail_user
    password:
      from_secret: mail_pass

trigger:
  status:
  - failure

depends_on:
- docs
