kind: pipeline
type: docker
name: docs

steps:
  - name: build
    image: hexpm/elixir:1.11.1-erlang-23.1.1-alpine-3.12.0
    environment:
      MIX_ENV: dev
    commands:
      - mix local.hex --force
      - mix local.rebar --force
      - mix deps.get --only dev
      - mix deps.compile
      - mix docs

trigger:
  branch:
    develop
  event:
    push
---
kind: pipeline
type: docker
name: test

steps:
  - name: test
    image: hexpm/elixir:1.11.1-erlang-23.1.1-alpine-3.12.0
    environment:
      MIX_ENV: test
    commands:
      - mix local.hex --force
      - mix local.rebar --force
      - mix deps.get --only dev
      - mix deps.compile
      - epmd -daemon
      - mix test
