kind: pipeline
type: docker
name: test

steps:
  - name: test
    image: elixir:latest
    environment:
      MIX_ENV: test
    commands:
      - mix local.hex --force
      - mix local.rebar --force
      - mix deps.get --only test
      - mix deps.compile
      - epmd -daemon
      - mix test

---
kind: pipeline
type: docker
name: typecheck

steps:
  - name: restore-plt-cache
    image: meltwater/drone-cache
    settings:
      backend: "filesystem"
      restore: true
      cache_key: "volume"
      mount:
        - '_build/dialyzer'
    volumes:
    - name: cache
      path: /tmp/cache

  - name: dialyzer
    image: elixir:latest
    environment:
      MIX_ENV: dev
    commands:
      - mix local.hex --force
      - mix local.rebar --force
      - mix deps.get --only dev
      - mix deps.compile
      - mix dialyzer --quiet --format short

  - name: rebuild-plt-cache
    image: meltwater/drone-cache
    settings:
      backend: "filesystem"
      rebuild: true
      cache_key: "volume"
      mount:
        - '_build/dialyzer'
    volumes:
    - name: cache
      path: /tmp/cache

volumes:
  - name: cache
    host:
      path: /var/cache/drone/
---
kind: pipeline
type: docker
name: installer

steps:
  - name: build
    image: elixir:latest
    environment:
      MIX_ENV: prod
    commands:
      - cd generator
      - mix archive.build -o skitter_new.ez

  - name: publish
    image: drillster/drone-rsync
    settings:
      hosts: [ soft.vub.ac.be ]
      user:
        from_secret: publish_ssh_user
      key:
        from_secret: publish_ssh_key
      include: [ "skitter_new.ez" ]
      exclude: [ "*" ]
      source: generator/
      target: ~/public_html/skitter/

depends_on:
- test
- typecheck
---
kind: pipeline
type: docker
name: docs

steps:
  - name: build
    image: elixir:latest
    environment:
      MIX_ENV: dev
      EX_DOC_PUBLIC: yes
    commands:
      - mix local.hex --force
      - mix local.rebar --force
      - mix deps.get --only dev
      - mix deps.compile
      - mix docs

  - name: publish
    image: drillster/drone-rsync
    settings:
      hosts: [ soft.vub.ac.be ]
      user:
        from_secret: publish_ssh_user
      key:
        from_secret: publish_ssh_key
      source: doc/
      target: ~/public_html/skitter/docs/${DRONE_TAG:-latest}
      recursive: true
      delete: true
    when:
      ref:
        - refs/heads/develop
        - refs/tags/*

depends_on:
- test
- typecheck
---

kind: pipeline
type: docker
name: notify-failure

clone:
  disable: true

steps:
- name: mail
  image: drillster/drone-email
  settings:
    host:
      from_secret: mail_host
    from:
      from_secret: mail_from
    username:
      from_secret: mail_user
    password:
      from_secret: mail_pass

trigger:
  status:
  - failure

depends_on:
- docs
- test
- typecheck
- installer
