kind: pipeline
type: docker
name: docs

steps:
  - name: build
    image: hexpm/elixir:1.11.2-erlang-23.1.2-alpine-3.12.1
    environment:
      MIX_ENV: dev
    commands:
      - mix local.hex --force
      - mix local.rebar --force
      - mix deps.get --only dev
      - mix deps.compile
      - mix docs

  - name: publish
    image: drillster/drone-rsync
    settings:
      hosts: [ soft.vub.ac.be ]
      user:
        from_secret: publish_ssh_user
      key:
        from_secret: publish_ssh_key
      source: doc/
      target: ~/public_html/skitter/docs/${DRONE_TAG:-latest}
      recursive: true
      delete: true
    when:
      ref:
        - refs/heads/develop
        - refs/tags/*

---
kind: pipeline
type: docker
name: test

steps:
  - name: test
    image: hexpm/elixir:1.11.2-erlang-23.1.2-alpine-3.12.1
    environment:
      MIX_ENV: test
    commands:
      - mix local.hex --force
      - mix local.rebar --force
      - mix deps.get --only dev
      - mix deps.compile
      - epmd -daemon
      - mix test

---
kind: pipeline
type: docker
name: build-x86_64-linux-musl

steps:
  - name: build
    image: hexpm/elixir:1.11.2-erlang-23.1.2-alpine-3.12.1
    environment:
      MIX_ENV: prod
    commands:
      - mkdir _build_target
      - mix local.hex --force
      - mix local.rebar --force
      - mix deps.get --only prod
      - mix deps.compile
      - mix release --path _build_target

  - name: tar
    image: alpine:3.12
    environment:
      TRIPLET: x86_64-unknown-linux-musl
      VERSION: ${DRONE_TAG:-latest}
    commands:
      - mv _build_target skitter.$VERSION.$TRIPLET
      - tar czf skitter.$VERSION.$TRIPLET.tar.gz skitter.$VERSION.$TRIPLET

  - name: publish
    image: drillster/drone-rsync
    settings:
      hosts: [ soft.vub.ac.be ]
      user:
        from_secret: publish_ssh_user
      key:
        from_secret: publish_ssh_key
      source: "*.tar.gz"
      target: ~/public_html/skitter/build/
    when:
      ref:
        - refs/heads/develop
        - refs/tags/*

# Only publish builds when tests pass
trigger:
  status:
  - success
depends_on:
- test

---
kind: pipeline
type: docker
name: build-x86_64-linux-gnu

steps:
  - name: build
    image: hexpm/elixir:1.11.2-erlang-23.1.2-debian-buster-20201012
    environment:
      MIX_ENV: prod
    commands:
      - mkdir _build_target
      - mix local.hex --force
      - mix local.rebar --force
      - mix deps.get --only prod
      - mix deps.compile
      - mix release --path _build_target

  - name: tar
    image: alpine:3.12
    environment:
      TRIPLET: x86_64-unknown-linux-gnu
      VERSION: ${DRONE_TAG:-latest}
    commands:
      - mv _build_target skitter.$VERSION.$TRIPLET
      - tar czf skitter.$VERSION.$TRIPLET.tar.gz skitter.$VERSION.$TRIPLET

  - name: publish
    image: drillster/drone-rsync
    settings:
      hosts: [ soft.vub.ac.be ]
      user:
        from_secret: publish_ssh_user
      key:
        from_secret: publish_ssh_key
      source: "*.tar.gz"
      target: ~/public_html/skitter/build/
    when:
      ref:
        - refs/heads/develop
        - refs/tags/*


# Only publish builds when tests pass
trigger:
  status:
  - success
depends_on:
- test
---
kind: pipeline
type: docker
name: notify-failure

clone:
  disable: true

steps:
- name: mail
  image: drillster/drone-email
  settings:
    host:
      from_secret: mail_host
    from:
      from_secret: mail_from
    username:
      from_secret: mail_user
    password:
      from_secret: mail_pass

trigger:
  status:
  - failure

depends_on:
- docs
- test
- build-x86_64-linux-gnu
- build-x86_64-linux-musl
